// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9ZN3TUPvYM7EiUoAW3kiuSRdmpiFCps',
    appId: '1:738880502085:web:6a121f201598d170f5e62c',
    messagingSenderId: '738880502085',
    projectId: 'reuniones-cunori',
    authDomain: 'reuniones-cunori.firebaseapp.com',
    storageBucket: 'reuniones-cunori.appspot.com',
    measurementId: 'G-W2DQW6QSBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZNKp_cM73jwikMI0tTC1uBx9-Qu1Ib28',
    appId: '1:738880502085:android:96cd413481bc576bf5e62c',
    messagingSenderId: '738880502085',
    projectId: 'reuniones-cunori',
    storageBucket: 'reuniones-cunori.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARW59mIW3rgW8aapjNOhuIsnJ8fHV3xz4',
    appId: '1:738880502085:ios:65b109c24e27a002f5e62c',
    messagingSenderId: '738880502085',
    projectId: 'reuniones-cunori',
    storageBucket: 'reuniones-cunori.appspot.com',
    iosClientId: '738880502085-hnt07pim69ncb1ckvqokomphc826fjdh.apps.googleusercontent.com',
    iosBundleId: 'cunori.edu.gt.reuniones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARW59mIW3rgW8aapjNOhuIsnJ8fHV3xz4',
    appId: '1:738880502085:ios:65b109c24e27a002f5e62c',
    messagingSenderId: '738880502085',
    projectId: 'reuniones-cunori',
    storageBucket: 'reuniones-cunori.appspot.com',
    iosClientId: '738880502085-hnt07pim69ncb1ckvqokomphc826fjdh.apps.googleusercontent.com',
    iosBundleId: 'cunori.edu.gt.reuniones',
  );
}
